//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer_RegistrationWCF.BL.Data
{
    public partial class Customer
    {
        public int Id { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public int PostalAddressId { get; set; }
        public int InvoiceAddressId { get; set; }
        public string Name { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
    }
}
